using System.IO;
using System.Text.Json;
using System.Windows;
namespace OpenFix;
public partial class MainWindow : Window
{
    private IReadOnlyList<Finding> findings = Array.Empty<Finding>();
    public MainWindow() { InitializeComponent(); if (ScanButton.Parent is System.Windows.Controls.StackPanel oldActions && oldActions.Parent is System.Windows.Controls.Grid grid) { var actions = new System.Windows.Controls.WrapPanel { HorizontalAlignment = System.Windows.HorizontalAlignment.Right, VerticalAlignment = VerticalAlignment.Center, MaxWidth = 410 }; while (oldActions.Children.Count > 0) { var child = oldActions.Children[0]; oldActions.Children.RemoveAt(0); actions.Children.Add(child); } var index = grid.Children.IndexOf(oldActions); grid.Children.RemoveAt(index); grid.Children.Insert(index, actions); AddActionButton(actions, "Enter product key", (_, _) => OpenActivationTool("3")); AddSettingsButton(actions, "Activation settings", "ms-settings:activation"); AddActionButton(actions, "Phone activation", (_, _) => OpenActivationTool("4")); AddSettingsButton(actions, "Storage settings", "ms-settings:storagesense"); AddSettingsButton(actions, "Windows Update", "ms-settings:windowsupdate"); AddSettingsButton(actions, "Network settings", "ms-settings:network-status"); } Opacity = 0; Loaded += (_, _) => BeginAnimation(OpacityProperty, new System.Windows.Media.Animation.DoubleAnimation(0, 1, TimeSpan.FromMilliseconds(260))); }
    private void AddActionButton(System.Windows.Controls.Panel panel, string label, RoutedEventHandler handler) { var button = new System.Windows.Controls.Button { Content = label, ToolTip = "Open the official Windows activation workflow", Padding = new Thickness(10, 8, 10, 8) }; button.Click += handler; panel.Children.Add(button); }
    private void OpenActivationTool(string mode) { try { System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("slui.exe", mode) { UseShellExecute = true }); EvidenceText.Text = mode == "3" ? "Windows product-key activation opened. Enter a valid key to activate this installation." : "Windows phone activation opened. Follow Microsoft’s official instructions."; } catch { OpenSettings("ms-settings:activation"); } }
    private void AddSettingsButton(System.Windows.Controls.Panel panel, string label, string uri) { var button = new System.Windows.Controls.Button { Content = label, ToolTip = "Open the official Windows settings page", Padding = new Thickness(10, 8, 10, 8) }; button.Click += (_, _) => OpenSettings(uri); panel.Children.Add(button); }
    private void OpenSettings(string uri) { try { System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(uri) { UseShellExecute = true }); } catch (Exception ex) { EvidenceText.Text = $"Could not open Windows settings: {ex.Message}"; } }
    private async void Scan_Click(object sender, RoutedEventArgs e) { ScanButton.IsEnabled = false; SummaryText.Text = "Inspecting system…"; EvidenceText.Text = "Reading evidence without changing settings."; try { findings = await Task.Run(OpenFixEngine.Scan); FindingsList.ItemsSource = findings.Select(f => $"{(f.Level == FindingLevel.Good ? "✓" : "!")}  {f.Title}\n    {f.Explanation}\n    Evidence: {f.Evidence}").ToArray(); var attention = findings.Count(f => f.Level != FindingLevel.Good); SummaryText.Text = attention == 0 ? "Your system looks healthy" : $"{attention} item(s) need review"; CountText.Text = $"{findings.Count} checks · {attention} requiring attention"; EvidenceText.Text = "Scan complete · no changes were applied."; ReportButton.IsEnabled = true; } catch (Exception ex) { SummaryText.Text = "Scan could not complete"; EvidenceText.Text = ex.Message; } finally { ScanButton.IsEnabled = true; } }
    private void Report_Click(object sender, RoutedEventArgs e) { if (findings.Count == 0) return; using var dialog = new System.Windows.Forms.SaveFileDialog { Filter = "OpenFix report (*.json)|*.json", FileName = "openfix-report.json" }; if (dialog.ShowDialog() == System.Windows.Forms.DialogResult.OK) File.WriteAllText(dialog.FileName, JsonSerializer.Serialize(findings, new JsonSerializerOptions { WriteIndented = true })); }
}
